// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./destinationRule";
export * from "./gateway";
export * from "./proxyConfig";
export * from "./serviceEntry";
export * from "./sidecar";
export * from "./virtualService";
export * from "./workloadEntry";

// Import resources to register:
import { DestinationRule } from "./destinationRule";
import { Gateway } from "./gateway";
import { ProxyConfig } from "./proxyConfig";
import { ServiceEntry } from "./serviceEntry";
import { Sidecar } from "./sidecar";
import { VirtualService } from "./virtualService";
import { WorkloadEntry } from "./workloadEntry";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:networking.istio.io/v1beta1:DestinationRule":
                return new DestinationRule(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:Gateway":
                return new Gateway(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:ProxyConfig":
                return new ProxyConfig(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:ServiceEntry":
                return new ServiceEntry(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:Sidecar":
                return new Sidecar(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:VirtualService":
                return new VirtualService(name, <any>undefined, { urn })
            case "kubernetes:networking.istio.io/v1beta1:WorkloadEntry":
                return new WorkloadEntry(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "networking.istio.io/v1beta1", _module)
