# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities
from . import outputs
from ._inputs import *
from pulumi_kubernetes import meta as _meta

__all__ = ['ApplicationArgs', 'Application']

@pulumi.input_type
class ApplicationArgs:
    def __init__(__self__, *,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']] = None,
                 operation: Optional[pulumi.Input['ApplicationOperationArgs']] = None,
                 spec: Optional[pulumi.Input['ApplicationSpecArgs']] = None,
                 status: Optional[pulumi.Input['ApplicationStatusArgs']] = None):
        """
        The set of arguments for constructing a Application resource.
        :param pulumi.Input['ApplicationOperationArgs'] operation: Operation contains information about a requested or running operation
        :param pulumi.Input['ApplicationSpecArgs'] spec: ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.
        :param pulumi.Input['ApplicationStatusArgs'] status: ApplicationStatus contains status information for the application
        """
        if api_version is not None:
            pulumi.set(__self__, "api_version", 'argoproj.io/v1alpha1')
        if kind is not None:
            pulumi.set(__self__, "kind", 'Application')
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if operation is not None:
            pulumi.set(__self__, "operation", operation)
        if spec is not None:
            pulumi.set(__self__, "spec", spec)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "api_version")

    @api_version.setter
    def api_version(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "api_version", value)

    @property
    @pulumi.getter
    def kind(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "kind", value)

    @property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']]:
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input['_meta.v1.ObjectMetaArgs']]):
        pulumi.set(self, "metadata", value)

    @property
    @pulumi.getter
    def operation(self) -> Optional[pulumi.Input['ApplicationOperationArgs']]:
        """
        Operation contains information about a requested or running operation
        """
        return pulumi.get(self, "operation")

    @operation.setter
    def operation(self, value: Optional[pulumi.Input['ApplicationOperationArgs']]):
        pulumi.set(self, "operation", value)

    @property
    @pulumi.getter
    def spec(self) -> Optional[pulumi.Input['ApplicationSpecArgs']]:
        """
        ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.
        """
        return pulumi.get(self, "spec")

    @spec.setter
    def spec(self, value: Optional[pulumi.Input['ApplicationSpecArgs']]):
        pulumi.set(self, "spec", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input['ApplicationStatusArgs']]:
        """
        ApplicationStatus contains status information for the application
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input['ApplicationStatusArgs']]):
        pulumi.set(self, "status", value)


class Application(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input[pulumi.InputType['_meta.v1.ObjectMetaArgs']]] = None,
                 operation: Optional[pulumi.Input[pulumi.InputType['ApplicationOperationArgs']]] = None,
                 spec: Optional[pulumi.Input[pulumi.InputType['ApplicationSpecArgs']]] = None,
                 status: Optional[pulumi.Input[pulumi.InputType['ApplicationStatusArgs']]] = None,
                 __props__=None):
        """
        Application is a definition of Application resource.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['ApplicationOperationArgs']] operation: Operation contains information about a requested or running operation
        :param pulumi.Input[pulumi.InputType['ApplicationSpecArgs']] spec: ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.
        :param pulumi.Input[pulumi.InputType['ApplicationStatusArgs']] status: ApplicationStatus contains status information for the application
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ApplicationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Application is a definition of Application resource.

        :param str resource_name: The name of the resource.
        :param ApplicationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_version: Optional[pulumi.Input[str]] = None,
                 kind: Optional[pulumi.Input[str]] = None,
                 metadata: Optional[pulumi.Input[pulumi.InputType['_meta.v1.ObjectMetaArgs']]] = None,
                 operation: Optional[pulumi.Input[pulumi.InputType['ApplicationOperationArgs']]] = None,
                 spec: Optional[pulumi.Input[pulumi.InputType['ApplicationSpecArgs']]] = None,
                 status: Optional[pulumi.Input[pulumi.InputType['ApplicationStatusArgs']]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationArgs.__new__(ApplicationArgs)

            __props__.__dict__["api_version"] = 'argoproj.io/v1alpha1'
            __props__.__dict__["kind"] = 'Application'
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["operation"] = operation
            __props__.__dict__["spec"] = spec
            __props__.__dict__["status"] = status
        super(Application, __self__).__init__(
            'kubernetes:argoproj.io/v1alpha1:Application',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Application':
        """
        Get an existing Application resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ApplicationArgs.__new__(ApplicationArgs)

        __props__.__dict__["api_version"] = None
        __props__.__dict__["kind"] = None
        __props__.__dict__["metadata"] = None
        __props__.__dict__["operation"] = None
        __props__.__dict__["spec"] = None
        __props__.__dict__["status"] = None
        return Application(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="apiVersion")
    def api_version(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "api_version")

    @property
    @pulumi.getter
    def kind(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "kind")

    @property
    @pulumi.getter
    def metadata(self) -> pulumi.Output['_meta.v1.outputs.ObjectMeta']:
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter
    def operation(self) -> pulumi.Output[Optional['outputs.ApplicationOperation']]:
        """
        Operation contains information about a requested or running operation
        """
        return pulumi.get(self, "operation")

    @property
    @pulumi.getter
    def spec(self) -> pulumi.Output['outputs.ApplicationSpec']:
        """
        ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.
        """
        return pulumi.get(self, "spec")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional['outputs.ApplicationStatus']]:
        """
        ApplicationStatus contains status information for the application
        """
        return pulumi.get(self, "status")

