// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Configuration.V1
{

    /// <summary>
    /// Ordering overrides the normal plugin execution order
    /// </summary>
    public class KongClusterPluginOrderingArgs : Pulumi.ResourceArgs
    {
        [Input("after")]
        private InputMap<ImmutableArray<string>>? _after;

        /// <summary>
        /// PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
        /// </summary>
        public InputMap<ImmutableArray<string>> After
        {
            get => _after ?? (_after = new InputMap<ImmutableArray<string>>());
            set => _after = value;
        }

        [Input("before")]
        private InputMap<ImmutableArray<string>>? _before;

        /// <summary>
        /// PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
        /// </summary>
        public InputMap<ImmutableArray<string>> Before
        {
            get => _before ?? (_before = new InputMap<ImmutableArray<string>>());
            set => _before = value;
        }

        public KongClusterPluginOrderingArgs()
        {
        }
    }
}
