# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_crds.argoproj as __argoproj
    argoproj = __argoproj
    import pulumi_crds.meta as __meta
    meta = __meta
else:
    argoproj = _utilities.lazy_import('pulumi_crds.argoproj')
    meta = _utilities.lazy_import('pulumi_crds.meta')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "crds",
  "mod": "argoproj.io/v1alpha1",
  "fqn": "pulumi_crds.argoproj.v1alpha1",
  "classes": {
   "kubernetes:argoproj.io/v1alpha1:Application": "Application"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "crds",
  "token": "pulumi:providers:crds",
  "fqn": "pulumi_crds",
  "class": "Provider"
 }
]
"""
)
