// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as v1alpha3 from "./v1alpha3";
import * as v1beta1 from "./v1beta1";

export {
    v1alpha3,
    v1beta1,
};
