# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from ... import _utilities

__all__ = [
    'WasmPluginSpecArgs',
    'WasmPluginSpecSelectorArgs',
]

@pulumi.input_type
class WasmPluginSpecArgs:
    def __init__(__self__, *,
                 image_pull_policy: Optional[pulumi.Input[str]] = None,
                 image_pull_secret: Optional[pulumi.Input[str]] = None,
                 phase: Optional[pulumi.Input[str]] = None,
                 plugin_config: Optional[pulumi.Input[Mapping[str, Any]]] = None,
                 plugin_name: Optional[pulumi.Input[str]] = None,
                 priority: Optional[pulumi.Input[int]] = None,
                 selector: Optional[pulumi.Input['WasmPluginSpecSelectorArgs']] = None,
                 sha256: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 verification_key: Optional[pulumi.Input[str]] = None):
        """
        Extend the functionality provided by the Istio proxy through WebAssembly filters. See more details at: https://istio.io/docs/reference/config/proxy_extensions/wasm-plugin.html
        :param pulumi.Input[str] image_pull_policy: The pull behaviour to be applied when fetching an OCI image.
        :param pulumi.Input[str] image_pull_secret: Credentials to use for OCI image pulling.
        :param pulumi.Input[str] phase: Determines where in the filter chain this `WasmPlugin` is to be injected.
        :param pulumi.Input[Mapping[str, Any]] plugin_config: The configuration that will be passed on to the plugin.
        :param pulumi.Input[int] priority: Determines ordering of `WasmPlugins` in the same `phase`.
        :param pulumi.Input[str] sha256: SHA256 checksum that will be used to verify Wasm module or OCI container.
        :param pulumi.Input[str] url: URL of a Wasm module or OCI container.
        """
        if image_pull_policy is not None:
            pulumi.set(__self__, "image_pull_policy", image_pull_policy)
        if image_pull_secret is not None:
            pulumi.set(__self__, "image_pull_secret", image_pull_secret)
        if phase is not None:
            pulumi.set(__self__, "phase", phase)
        if plugin_config is not None:
            pulumi.set(__self__, "plugin_config", plugin_config)
        if plugin_name is not None:
            pulumi.set(__self__, "plugin_name", plugin_name)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if selector is not None:
            pulumi.set(__self__, "selector", selector)
        if sha256 is not None:
            pulumi.set(__self__, "sha256", sha256)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if verification_key is not None:
            pulumi.set(__self__, "verification_key", verification_key)

    @property
    @pulumi.getter(name="imagePullPolicy")
    def image_pull_policy(self) -> Optional[pulumi.Input[str]]:
        """
        The pull behaviour to be applied when fetching an OCI image.
        """
        return pulumi.get(self, "image_pull_policy")

    @image_pull_policy.setter
    def image_pull_policy(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "image_pull_policy", value)

    @property
    @pulumi.getter(name="imagePullSecret")
    def image_pull_secret(self) -> Optional[pulumi.Input[str]]:
        """
        Credentials to use for OCI image pulling.
        """
        return pulumi.get(self, "image_pull_secret")

    @image_pull_secret.setter
    def image_pull_secret(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "image_pull_secret", value)

    @property
    @pulumi.getter
    def phase(self) -> Optional[pulumi.Input[str]]:
        """
        Determines where in the filter chain this `WasmPlugin` is to be injected.
        """
        return pulumi.get(self, "phase")

    @phase.setter
    def phase(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "phase", value)

    @property
    @pulumi.getter(name="pluginConfig")
    def plugin_config(self) -> Optional[pulumi.Input[Mapping[str, Any]]]:
        """
        The configuration that will be passed on to the plugin.
        """
        return pulumi.get(self, "plugin_config")

    @plugin_config.setter
    def plugin_config(self, value: Optional[pulumi.Input[Mapping[str, Any]]]):
        pulumi.set(self, "plugin_config", value)

    @property
    @pulumi.getter(name="pluginName")
    def plugin_name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "plugin_name")

    @plugin_name.setter
    def plugin_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "plugin_name", value)

    @property
    @pulumi.getter
    def priority(self) -> Optional[pulumi.Input[int]]:
        """
        Determines ordering of `WasmPlugins` in the same `phase`.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "priority", value)

    @property
    @pulumi.getter
    def selector(self) -> Optional[pulumi.Input['WasmPluginSpecSelectorArgs']]:
        return pulumi.get(self, "selector")

    @selector.setter
    def selector(self, value: Optional[pulumi.Input['WasmPluginSpecSelectorArgs']]):
        pulumi.set(self, "selector", value)

    @property
    @pulumi.getter
    def sha256(self) -> Optional[pulumi.Input[str]]:
        """
        SHA256 checksum that will be used to verify Wasm module or OCI container.
        """
        return pulumi.get(self, "sha256")

    @sha256.setter
    def sha256(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sha256", value)

    @property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[str]]:
        """
        URL of a Wasm module or OCI container.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url", value)

    @property
    @pulumi.getter(name="verificationKey")
    def verification_key(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "verification_key")

    @verification_key.setter
    def verification_key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "verification_key", value)


@pulumi.input_type
class WasmPluginSpecSelectorArgs:
    def __init__(__self__, *,
                 match_labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None):
        if match_labels is not None:
            pulumi.set(__self__, "match_labels", match_labels)

    @property
    @pulumi.getter(name="matchLabels")
    def match_labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        return pulumi.get(self, "match_labels")

    @match_labels.setter
    def match_labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "match_labels", value)


