// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

import {ObjectMeta} from "../meta/v1";

export namespace configuration {
    export namespace v1 {
        /**
         * ConfigFrom references a secret containing the plugin configuration.
         */
        export interface KongClusterPluginConfigfromArgs {
            /**
             * NamespacedSecretValueFromSource represents the source of a secret value specifying the secret namespace
             */
            secretKeyRef?: pulumi.Input<inputs.configuration.v1.KongClusterPluginConfigfromSecretkeyrefArgs>;
        }

        /**
         * NamespacedSecretValueFromSource represents the source of a secret value specifying the secret namespace
         */
        export interface KongClusterPluginConfigfromSecretkeyrefArgs {
            /**
             * the key containing the value
             */
            key: pulumi.Input<string>;
            /**
             * the secret containing the key
             */
            name: pulumi.Input<string>;
            /**
             * The namespace containing the secret
             */
            namespace: pulumi.Input<string>;
        }

        /**
         * Ordering overrides the normal plugin execution order
         */
        export interface KongClusterPluginOrderingArgs {
            /**
             * PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
             */
            after?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
            /**
             * PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
             */
            before?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>}>;
        }

    }
}
