// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

import {ObjectMeta} from "../meta/v1";

export namespace configuration {
    export namespace v1 {
        /**
         * ConfigFrom references a secret containing the plugin configuration.
         */
        export interface KongClusterPluginConfigfrom {
            /**
             * NamespacedSecretValueFromSource represents the source of a secret value specifying the secret namespace
             */
            secretKeyRef?: outputs.configuration.v1.KongClusterPluginConfigfromSecretkeyref;
        }

        /**
         * NamespacedSecretValueFromSource represents the source of a secret value specifying the secret namespace
         */
        export interface KongClusterPluginConfigfromSecretkeyref {
            /**
             * the key containing the value
             */
            key: string;
            /**
             * the secret containing the key
             */
            name: string;
            /**
             * The namespace containing the secret
             */
            namespace: string;
        }

        /**
         * Ordering overrides the normal plugin execution order
         */
        export interface KongClusterPluginOrdering {
            /**
             * PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
             */
            after?: {[key: string]: string[]};
            /**
             * PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
             */
            before?: {[key: string]: string[]};
        }

    }
}
