// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Configuration.V1
{

    /// <summary>
    /// Ordering overrides the normal plugin execution order
    /// </summary>
    [OutputType]
    public sealed class KongClusterPluginOrdering
    {
        /// <summary>
        /// PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableArray<string>> After;
        /// <summary>
        /// PluginOrderingPhase indicates which plugins in a phase should affect the target plugin's order
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableArray<string>> Before;

        [OutputConstructor]
        private KongClusterPluginOrdering(
            ImmutableDictionary<string, ImmutableArray<string>> after,

            ImmutableDictionary<string, ImmutableArray<string>> before)
        {
            After = after;
            Before = before;
        }
    }
}
