// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Configuration.V1
{

    /// <summary>
    /// ConfigFrom references a secret containing the plugin configuration.
    /// </summary>
    [OutputType]
    public sealed class KongClusterPluginConfigfrom
    {
        /// <summary>
        /// NamespacedSecretValueFromSource represents the source of a secret value specifying the secret namespace
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Configuration.V1.KongClusterPluginConfigfromSecretkeyref SecretKeyRef;

        [OutputConstructor]
        private KongClusterPluginConfigfrom(Pulumi.Kubernetes.Types.Outputs.Configuration.V1.KongClusterPluginConfigfromSecretkeyref secretKeyRef)
        {
            SecretKeyRef = secretKeyRef;
        }
    }
}
